# Generated by Django 3.2.15 on 2024-12-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_profile_nama_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toko',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='notif',
            name='penjualan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.penjualan'),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penjualanproduk',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
    ]
