# Generated by Django 3.2.15 on 2024-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20241220_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='bukti_transfer',
            field=models.FileField(blank=True, null=True, upload_to='images/bukti/'),
        ),
    ]
